### ISSUE TITLE
Query about being compelled to act

### ISSUE THREAD

**Issue by ktinto** [ldeo-glaciology/ITGC-field-doc#7]
As written, I question the key policy that no one can be compelled to do something they don't want to, and should not have to justify their refusal.  I see the value in empowering each person to keep themselves safe, but also the danger in not having open communication about what makes the situation unsafe.  The phrasing also leaves teams vulnerable to bad actors (or misunderstandings), where safety can be compromised by refusal to help a teammate. I think it might be important that the reason be divulged.

**Comment by jkingslake** [comment]
Thanks so much for reading through the document and for bringing this up! 

It's an important point and I am interested to hear what others think about it. 

I think the original reason for mentioning that people did not need to do divulge the reason for not wanting to do something was that it potentially could help in scenarios where people feel uncomfortable talking about the reasons. 

One example that springs to mind is when someone is being asked to spend time alone with someone who they are uncomfortable with (for whatever reason), but may not want to bring this up in a field/ship situation for fear of exacerbating the situation or of some form of retribution. Of course, the best scenario would be that they do feel ok bring it up and everything is resolved in the field/ship. This would be best for the safety reason you mention and also because having people carry these worries around with them would be highly stressful and not at all what we would want. Nonetheless, it is understandable that there would be scenarios when they would not want to bring up concerns and so may feel compelled to be in a situation they are not comfortable with. 

Maybe we can say (paraphrasing here) 
"With the exception of cases when there is a safety concern, as determined by the field team leader, people cant be compelled to do anything they dont want to do and dont need to give a reason, but are encouraged to openly discussed any concerns whenever they feel able to do so."

What do others think?

**Comment by iexploreice** [comment]
I agree that the wording could be improved. And what you wrote is headed in the right direction:

I'd suggest a variation:

A team member cannot be compelled to do anything they feel will make
them uncomfortable or unsafe. While they are encouraged to voice their
reasoning behind this choice in order to keep everyone safe and to
suggest alternatives that they would feel comfortable with, ultimately,
they do not need to explain their reasoning, if they don't want to.  In
situations where team safety is a concern, however, field leaders have
the discretion to request more information (privately if necessary) as
needed to ensure overall team safety. In these situations, the field
leaders must do their best to make a change in the plan or activity to
ensure the team member feels safer.

Is it too long??

**Comment by columbiaclimatecenter** [comment]
I like the wording Erin suggested, and it conveys the intent you expressed Jonny which is important.

**Comment by emma-c-smith** [comment]
Thanks for bringing this up Kirsty, this is a very good point. I like Erin's suggested wording too and would be happy to go forward with that.

**Comment by jkingslake** [comment]
@ktinto, what do you think of @iexploreice's wording? 

If you are happy I will make the edit in the main text and leave the statement in the appendix (the example team agreement) unchanged.

**Comment by jkingslake** [comment]
I merged the change after speaking to @ktinto in person.
